version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    image: immu-db-apis:latest
    ports:
      - "10000:10000"
    expose:
      - "10000"
    volumes:
      - ./backend:/go/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    image: immu-db-fe:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    links:
      - backend
